import Link from "next/link";
import { redirect } from "next/navigation";
import { AdminShell } from "../../../../components/admin-shell";
import { requireCurrentUser } from "../../../../lib/auth";
import { listTenantMedia } from "../../../../lib/media";
import { listMediaConsents, listModerationCases } from "../../../../lib/moderation";
import { requireTenantPermission } from "../../../../lib/tenant";
import { hideMediaAction, moderateCommentAction, registerConsentAction, revokeConsentAction } from "./actions";

export const dynamic = "force-dynamic";

export default async function ModerationPage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ consentimento?: string; revogado?: string; oculto?: string; moderado?: string; erro?: string }> }) {
  const user = await requireCurrentUser(); const { slug } = await params;
  let tenant; let canManageMedia = false; let canModerateComments = false;
  try { tenant = await requireTenantPermission(slug, user, "comments.moderate"); canModerateComments = true; }
  catch { try { tenant = await requireTenantPermission(slug, user, "media.upload"); canManageMedia = true; } catch { redirect(`/admin/${slug}?erro=acesso-negado`); } }
  if (canModerateComments && tenant) canManageMedia = await (async () => { try { await requireTenantPermission(slug, user, "media.upload"); return true; } catch { return false; } })();
  const [media, consents, cases] = await Promise.all([canManageMedia ? listTenantMedia(tenant.id, user.id) : Promise.resolve([]), canManageMedia ? listMediaConsents(tenant.id, user.id) : Promise.resolve([]), canModerateComments || canManageMedia ? listModerationCases(tenant.id, user.id, { includeComments: canModerateComments, includeMedia: canManageMedia }) : Promise.resolve([])]);
  const { consentimento, revogado, oculto, moderado, erro } = await searchParams;
  return <AdminShell tenantName={tenant.displayName} tenantSlug={tenant.slug} userName={user.displayName} isSuperuser={user.isSuperuser} activeSection="moderation"><main className="admin-content">
    <div className="admin-title"><div><span className="eyebrow dark">PROTEÇÃO E CONVIVÊNCIA</span><h1>Moderação do clube.</h1><p>Analise denúncias de comentários e mídias dentro da permissão recebida; todas as decisões ficam auditadas.</p></div><Link className="button button-secondary" href={`/admin/${slug}`}>Voltar ao painel</Link></div>
    {(consentimento || revogado || oculto || moderado) && <p className="form-success">A operação foi registrada e auditada.</p>}{erro && <p className="form-error">{erro}</p>}
    {canManageMedia && <>
      <section className="panel form-panel"><header><div><span className="eyebrow dark">CONSENTIMENTO</span><h2>Vincular documento externo</h2></div></header><form action={registerConsentAction} className="form-grid"><input type="hidden" name="slug" value={slug} /><label className="form-grid-wide">Mídia<select name="mediaId" required><option value="">Escolha uma imagem</option>{media.map((asset) => <option key={asset.id} value={asset.id}>{asset.originalFilename}</option>)}</select></label><label>Referência da pessoa<input name="subjectReference" required /></label><label>Referência do documento<input name="documentReference" required /></label><label>Responsável (se aplicável)<input name="guardianName" /></label><label>E-mail do responsável<input name="guardianEmail" type="email" /></label><label>Validade<input name="validUntil" type="date" /></label><div className="form-actions"><button className="button button-secondary">Registrar consentimento</button></div></form></section>
      <section className="panel people-panel"><header><div><span className="eyebrow dark">CONSENTIMENTOS</span><h2>Revogação imediata</h2></div></header><div className="people-list">{consents.map((consent) => <article key={consent.id}><div><b>{consent.originalFilename ?? "Documento sem mídia"}</b><small>{consent.subjectReference} · {consent.externalDocumentReference} · {consent.revokedAt ? "revogado" : "ativo"}</small></div>{!consent.revokedAt && <form className="people-actions" action={revokeConsentAction}><input type="hidden" name="slug" value={slug} /><input type="hidden" name="consentId" value={consent.id} /><input name="reason" placeholder="Motivo da revogação" required /><button className="button button-secondary">Revogar e ocultar</button></form>}</article>)}{!consents.length && <p>Nenhum consentimento registrado.</p>}</div></section>
      <section className="panel people-panel"><header><div><span className="eyebrow dark">DENÚNCIA DE MÍDIA</span><h2>Ocultação preventiva</h2></div></header><div className="people-list">{media.map((asset) => <article key={asset.id}><div><b>{asset.originalFilename}</b><small>{asset.processingStatus}</small></div><form className="people-actions" action={hideMediaAction}><input type="hidden" name="slug" value={slug} /><input type="hidden" name="mediaId" value={asset.id} /><input name="reason" placeholder="Motivo da denúncia" required /><button className="button button-secondary">Ocultar para análise</button></form></article>)}{!media.length && <p>Envie uma imagem para iniciar a moderação.</p>}</div></section>
    </>}
    {(canModerateComments || canManageMedia) && <section className="panel people-panel"><header><div><span className="eyebrow dark">FILA DE MODERAÇÃO</span><h2>Prazo de análise: 24 horas</h2></div></header><div className="people-list">{cases.map((item) => <article key={item.id} className="moderation-case"><div><b>{item.caseType === "COMMENT_REPORT" || item.caseType === "COMMENT_MODERATION" ? `Comentário de ${item.commentAuthor ?? "membro"} · ${item.status}` : `${item.originalFilename ?? "Mídia"} · ${item.status}`}</b><small>Prazo: {new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(item.dueAt)} · {item.reason}</small>{item.commentBody && <blockquote>{item.commentBody}</blockquote>}</div><span className="status-pill">{item.priority}</span>{item.commentId && canModerateComments && !["RESOLVED", "CLOSED"].includes(item.status) && <form className="moderation-decision" action={moderateCommentAction}><input type="hidden" name="slug" value={slug} /><input type="hidden" name="commentId" value={item.commentId} /><label>Justificativa<textarea name="reason" maxLength={1000} required /></label><div><button className="button button-secondary" name="decision" value="KEEP">Manter visível</button><button className="button button-secondary" name="decision" value="HIDE">Ocultar</button><button className="button button-primary" name="decision" value="REMOVE">Remover</button></div></form>}</article>)}{!cases.length && <p>Nenhuma denúncia aberta.</p>}</div></section>}
  </main></AdminShell>;
}
